import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/navbar/page.jsx";
import { Jost } from 'next/font/google';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Mohammed Ismail | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased bg-[#1D1B19] text-white`} >
        <div className="grid md:grid-cols-6 2xl:grid-cols-5">
          <div className="md:col-span-2 2xl:col-span-1">
            <Navbar />
          </div>
          <main className="md:col-span-4 2xl:col-span-4">
            <section className="md:w-11/12 w-4/5 mx-auto pt-16 md:pt-5">
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
